### ISSUE TITLE
Create config loading from .yaml files

### ISSUE THREAD

**Issue by pavleprica** [go-nag/configuration#1]
We would like to achieve to have the possibility to load predefined `.yaml` files for loading app configuration. 

To give an example:
Let's assume we have three environments. 

- local
- dev
- prod

For the `local` environment, we could be free to specify any values, not being worried about security. For example if you are running a local postgress version, you don't mind if you commit the file with `password: 12345`.

Though for the `dev` and prod environment, we would want to abstract that to being read from a environment variable. So it would look more like `password: ${DB_PASSWORD}`.

An example of file content

`config-local.yaml`
```yaml
database:
  username: user
  password: my-secret-pw
```

`config-dev.yaml`
```yaml
database:
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
```

In the `config-dev.yaml` example, it will load the environment config, and load from the system environment the values for these keys.

This of course has to be available and accessible through code for fetching values.
