### ISSUE TITLE
Add support for loading arrays

### ISSUE THREAD

**Issue by pavleprica** [go-nag/configuration#3]
In yaml files, or better said yaml syntax, arrays are supported. While the current loader does not support it.
It would be beneficial to add support for loading arrays.

For example:
```yaml
kafka:
    broker-urls:
        - http://host1.com
        - http://host2.com
        - http://host3.com
```
